version: '3.1'

services:
  redis:
    image: redis
    ports:
      - "6380:6379"
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
